export const doctorsData = [
  {
    name: 'Dr. Emily Carter',
    specialty: 'General',
    rating: 4.7,
    image: "",
    consultationCharge: 85,
    hospital: 'Green Valley Medical Center',
    yearsOfPractice: 10,
    details: 'Experienced in primary care and general health checkups for all age groups.',
  },
  {
    name: 'Dr. James Foster',
    specialty: 'General',
    rating: 4.9,
    image: "",
    consultationCharge: 95,
    hospital: 'Sunrise Family Clinic',
    yearsOfPractice: 15,
    details: 'Skilled in diagnosing and treating common medical conditions, providing preventive care.',
  },
  {
    name: 'Dr. Olivia Bennett',
    specialty: 'General',
    rating: 4.8,
    image: "",
    consultationCharge: 80,
    hospital: 'Metro Health Care',
    yearsOfPractice: 12,
    details: 'Specialist in general consultations, focusing on adult health and preventive medicine.',
  },
  {
    name: 'Dr. William Harris',
    specialty: 'General',
    rating: 4.6,
    image: "",
    consultationCharge: 90,
    hospital: 'Lakeside Medical Clinic',
    yearsOfPractice: 14,
    details: 'Expert in managing chronic diseases and providing routine health checkups.',
  },
  {
    name: 'Dr. Sophia Turner',
    specialty: 'General',
    rating: 4.7,
    image: "",
    consultationCharge: 85,
    hospital: 'City Health Clinic',
    yearsOfPractice: 9,
    details: 'Providing comprehensive medical care for individuals and families.',
  },
  {
    name: 'Dr. Michael Robinson',
    specialty: 'General',
    rating: 4.5,
    image: "",
    consultationCharge: 92,
    hospital: 'Downtown Medical Plaza',
    yearsOfPractice: 13,
    details: 'Focuses on preventive care and the management of common illnesses.',
  },
  {
    name: 'Dr. Emma Scott',
    specialty: 'General',
    rating: 4.9,
    image: "",
    consultationCharge: 88,
    hospital: 'Sunshine Family Health',
    yearsOfPractice: 11,
    details: 'Experienced in treating common medical conditions and promoting general wellness.',
  },
  {
    name: 'Dr. Jack Adams',
    specialty: 'General',
    rating: 4.8,
    image: "",
    consultationCharge: 100,
    hospital: 'River Valley Clinic',
    yearsOfPractice: 16,
    details: 'Specialist in general medicine with a focus on adult preventive care.',
  },
  {
    name: 'Dr. Ava Murphy',
    specialty: 'General',
    rating: 4.6,
    image: "",
    consultationCharge: 83,
    hospital: 'Evergreen Medical Center',
    yearsOfPractice: 8,
    details: 'Provides medical care for common illnesses and chronic disease management.',
  },
  {
    name: 'Dr. Henry Peterson',
    specialty: 'General',
    rating: 4.7,
    image: "",
    consultationCharge: 87,
    hospital: 'Oceanview Family Clinic',
    yearsOfPractice: 10,
    details: 'Focuses on patient-centered care and disease prevention strategies.',
  },
  {
    name: 'Dr. Mia Cooper',
    specialty: 'General',
    rating: 4.8,
    image: "",
    consultationCharge: 85,
    hospital: 'Central City Health Clinic',
    yearsOfPractice: 9,
    details: 'Expert in managing a variety of medical conditions, with a focus on wellness.',
  },
  {
    name: 'Dr. Luke Mitchell',
    specialty: 'General',
    rating: 4.9,
    image: "",
    consultationCharge: 92,
    hospital: 'Horizon Family Clinic',
    yearsOfPractice: 14,
    details: 'Provides comprehensive health care and focuses on preventive health strategies.',
  },
  {
    name: 'Dr. Isabella Young',
    specialty: 'General',
    rating: 4.7,
    image: "",
    consultationCharge: 86,
    hospital: 'Westside Health Clinic',
    yearsOfPractice: 10,
    details: 'Experienced in general health care and the management of long-term conditions.',
  },
  {
    name: 'Dr. Elijah Brooks',
    specialty: 'General',
    rating: 4.6,
    image: "",
    consultationCharge: 90,
    hospital: 'Highland Medical Center',
    yearsOfPractice: 12,
    details: 'Specializes in family health care and chronic disease prevention.',
  },
  {
    name: 'Dr. Charlotte Reed',
    specialty: 'General',
    rating: 4.8,
    image: "",
    consultationCharge: 93,
    hospital: 'Blue Ridge Medical Center',
    yearsOfPractice: 13,
    details: 'Expert in family medicine and promoting preventive health care.',
  },
  {
    name: 'Dr. Daniel Morgan',
    specialty: 'General',
    rating: 4.5,
    image: "",
    consultationCharge: 89,
    hospital: 'Maplewood Family Clinic',
    yearsOfPractice: 11,
    details: 'Provides general health care services with a focus on early diagnosis.',
  },
  {
    name: 'Dr. Harper Collins',
    specialty: 'General',
    rating: 4.9,
    image: "",
    consultationCharge: 91,
    hospital: 'Clearview Medical Center',
    yearsOfPractice: 12,
    details: 'Skilled in managing various medical conditions and promoting preventive care.',
  },
  {
    name: 'Dr. Benjamin Ward',
    specialty: 'General',
    rating: 4.8,
    image: "",
    consultationCharge: 95,
    hospital: 'Seaside Family Clinic',
    yearsOfPractice: 15,
    details: 'Specialist in adult health care and general medical consultations.',
  },
  {
    name: 'Dr. Grace Parker',
    specialty: 'General',
    rating: 4.7,
    image: "",
    consultationCharge: 88,
    hospital: 'Pine Grove Health Center',
    yearsOfPractice: 9,
    details: 'Provides holistic medical care with a focus on patient wellness.',
  },
  {
    name: 'Dr. Jackson Lewis',
    specialty: 'General',
    rating: 4.6,
    image: "",
    consultationCharge: 90,
    hospital: 'Forest Hills Medical Center',
    yearsOfPractice: 13,
    details: 'Experienced in primary care, treating a wide range of medical conditions.',
  },
  {
    name: 'Dr. Sarah Johnson',
    specialty: 'Dentist',
    rating: 4.9,
    image: "",
    consultationCharge: 120,
    hospital: 'Bright Smile Dental Clinic',
    yearsOfPractice: 14,
    details: 'Expert in cosmetic dentistry, specializing in teeth whitening and veneers.',
  },
  {
    name: 'Dr. Matthew Lee',
    specialty: 'Dentist',
    rating: 4.8,
    image: "",
    consultationCharge: 110,
    hospital: 'Downtown Dental Care',
    yearsOfPractice: 12,
    details: 'Specializes in root canal treatments and restorative dentistry.',
  },
  {
    name: 'Dr. Amanda Clark',
    specialty: 'Dentist',
    rating: 4.7,
    image: "",
    consultationCharge: 105,
    hospital: 'Smiles for Life Dentistry',
    yearsOfPractice: 10,
    details: 'Focuses on preventive dental care and pediatric dentistry.',
  },
  {
    name: 'Dr. David Martinez',
    specialty: 'Dentist',
    rating: 4.6,
    image: "",
    consultationCharge: 115,
    hospital: 'Pearl Dental Clinic',
    yearsOfPractice: 13,
    details: 'Experienced in dental implants and full mouth rehabilitation.',
  },
  {
    name: 'Dr. Lily Hernandez',
    specialty: 'Dentist',
    rating: 4.9,
    image: "",
    consultationCharge: 125,
    hospital: 'Perfect Smile Dental Care',
    yearsOfPractice: 15,
    details: 'Expert in orthodontics, offering braces and Invisalign treatments.',
  },
  {
    name: 'Dr. Ethan Brooks',
    specialty: 'Dentist',
    rating: 4.5,
    image: "",
    consultationCharge: 108,
    hospital: 'Evergreen Dental Clinic',
    yearsOfPractice: 11,
    details: 'Focuses on family dentistry and comprehensive oral health care.',
  },
  {
    name: 'Dr. Chloe Green',
    specialty: 'Dentist',
    rating: 4.8,
    image: "",
    consultationCharge: 112,
    hospital: 'Healthy Smiles Dental Care',
    yearsOfPractice: 9,
    details: 'Specialist in restorative dentistry and cosmetic dental procedures.',
  },
  {
    name: 'Dr. Noah Foster',
    specialty: 'Dentist',
    rating: 4.7,
    image: "",
    consultationCharge: 115,
    hospital: 'City Dental Clinic',
    yearsOfPractice: 12,
    details: 'Expert in oral surgery and wisdom tooth extractions.',
  },
  {
    name: 'Dr. Mia Carter',
    specialty: 'Dentist',
    rating: 4.6,
    image: "",
    consultationCharge: 110,
    hospital: 'Sunrise Dental Center',
    yearsOfPractice: 8,
    details: 'Focuses on dental hygiene and preventive dental care for all ages.',
  },
  {
    name: 'Dr. Oliver Evans',
    specialty: 'Dentist',
    rating: 4.8,
    image: "",
    consultationCharge: 120,
    hospital: 'Oceanview Dental Care',
    yearsOfPractice: 13,
    details: 'Experienced in full mouth rehabilitation and dental crowns.',
  },
  {
    name: 'Dr. Emily King',
    specialty: 'Dentist',
    rating: 4.7,
    image: "",
    consultationCharge: 115,
    hospital: 'River Valley Dental Clinic',
    yearsOfPractice: 10,
    details: 'Expert in pediatric dentistry and dental care for children.',
  },
  {
    name: 'Dr. Jackson Walker',
    specialty: 'Dentist',
    rating: 4.9,
    image: "",
    consultationCharge: 118,
    hospital: 'Central Dental Health Clinic',
    yearsOfPractice: 15,
    details: 'Specialist in periodontics, focusing on gum disease treatments.',
  },
  {
    name: 'Dr. Grace Lewis',
    specialty: 'Dentist',
    rating: 4.8,
    image: "",
    consultationCharge: 125,
    hospital: 'Horizon Dental Care',
    yearsOfPractice: 12,
    details: 'Provides cosmetic dentistry, including veneers and smile makeovers.',
  },
  {
    name: 'Dr. William Ramirez',
    specialty: 'Dentist',
    rating: 4.7,
    image: "",
    consultationCharge: 115,
    hospital: 'Blue Ridge Dental Center',
    yearsOfPractice: 14,
    details: 'Expert in dental implants and complex oral surgery procedures.',
  },
  {
    name: 'Dr. Ava Adams',
    specialty: 'Dentist',
    rating: 4.9,
    image: "",
    consultationCharge: 120,
    hospital: 'Highland Dental Clinic',
    yearsOfPractice: 11,
    details: 'Experienced in orthodontics, focusing on Invisalign and braces.',
  },
  {
    name: 'Dr. Benjamin Reed',
    specialty: 'Dentist',
    rating: 4.8,
    image: "",
    consultationCharge: 110,
    hospital: 'Seaside Dental Clinic',
    yearsOfPractice: 13,
    details: 'Focuses on preventive dental care and general dentistry.',
  },
  {
    name: 'Dr. Isabella Morgan',
    specialty: 'Dentist',
    rating: 4.7,
    image: "",
    consultationCharge: 112,
    hospital: 'Clearview Dental Care',
    yearsOfPractice: 10,
    details: 'Expert in restorative dentistry and full mouth reconstructions.',
  },
  {
    name: 'Dr. Lucas Powell',
    specialty: 'Dentist',
    rating: 4.6,
    image: "",
    consultationCharge: 118,
    hospital: 'Maplewood Dental Clinic',
    yearsOfPractice: 12,
    details: 'Specialist in cosmetic dentistry, including teeth whitening and bonding.',
  },
  {
    name: 'Dr. Sophia Turner',
    specialty: 'Dentist',
    rating: 4.9,
    image: "",
    consultationCharge: 125,
    hospital: 'Pine Grove Dental Clinic',
    yearsOfPractice: 14,
    details: 'Provides dental implants, crowns, and bridges with a focus on aesthetics.',
  },
  {
    name: 'Dr. Henry Cooper',
    specialty: 'Dentist',
    rating: 4.7,
    image: "",
    consultationCharge: 115,
    hospital: 'Forest Hills Dental Clinic',
    yearsOfPractice: 11,
    details: 'Focuses on endodontics, including root canals and retreatments.',
  },
  {
    name: 'Dr. James Carter',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: "",
    consultationCharge: 180,
    hospital: 'Heart Care Clinic',
    yearsOfPractice: 16,
    details: 'Specializes in heart disease prevention and cardiovascular treatments.',
  },
  {
    name: 'Dr. Olivia Miller',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: "",
    consultationCharge: 190,
    hospital: 'Cardio Wellness Center',
    yearsOfPractice: 14,
    details: 'Expert in managing hypertension and coronary artery disease.',
  },
  {
    name: 'Dr. Michael Harris',
    specialty: 'Cardiologist',
    rating: 4.7,
    image: "",
    consultationCharge: 200,
    hospital: 'Elite Heart Institute',
    yearsOfPractice: 18,
    details: 'Specializes in non-invasive cardiac diagnostics and heart failure management.',
  },
  {
    name: 'Dr. Emma Martinez',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: "",
    consultationCharge: 185,
    hospital: 'Pulse Cardiology Clinic',
    yearsOfPractice: 13,
    details: 'Focuses on interventional cardiology and cardiac catheterization.',
  },
  {
    name: 'Dr. William Thompson',
    specialty: 'Cardiologist',
    rating: 4.6,
    image: "",
    consultationCharge: 175,
    hospital: 'Vascular & Heart Specialists',
    yearsOfPractice: 15,
    details: 'Expert in electrophysiology and arrhythmia management.',
  },
  {
    name: 'Dr. Sophia Robinson',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: "",
    consultationCharge: 195,
    hospital: 'Healthy Heart Clinic',
    yearsOfPractice: 12,
    details: 'Specializes in preventive cardiology and heart disease in women.',
  },
  {
    name: 'Dr. Daniel Lee',
    specialty: 'Cardiologist',
    rating: 4.7,
    image: "",
    consultationCharge: 185,
    hospital: 'Cardio Life Clinic',
    yearsOfPractice: 11,
    details: 'Focuses on congestive heart failure and cardiac rehabilitation.',
  },
  {
    name: 'Dr. Ava Lewis',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: "",
    consultationCharge: 210,
    hospital: 'Metropolitan Heart Institute',
    yearsOfPractice: 17,
    details: 'Expert in angioplasty, stent placements, and cardiovascular interventions.',
  },
  {
    name: 'Dr. Ethan Walker',
    specialty: 'Cardiologist',
    rating: 4.6,
    image: "",
    consultationCharge: 180,
    hospital: 'Heartbeat Specialists',
    yearsOfPractice: 14,
    details: 'Specializes in valve disease and echocardiography.',
  },
  {
    name: 'Dr. Isabella Young',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: "",
    consultationCharge: 190,
    hospital: 'Pioneer Cardiology Clinic',
    yearsOfPractice: 13,
    details: 'Focuses on heart rhythm disorders and implantable cardiac devices.',
  },
  {
    name: 'Dr. Alexander Hill',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: "",
    consultationCharge: 215,
    hospital: 'Vanguard Heart Institute',
    yearsOfPractice: 20,
    details: 'Specializes in cardiac surgery, including bypass surgery and valve replacements.',
  },
  {
    name: 'Dr. Emily Adams',
    specialty: 'Cardiologist',
    rating: 4.7,
    image: "",
    consultationCharge: 195,
    hospital: 'Comprehensive Cardiac Care',
    yearsOfPractice: 16,
    details: 'Expert in managing arrhythmias and advanced heart failure.',
  },
  {
    name: 'Dr. Mason King',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: "",
    consultationCharge: 180,
    hospital: 'Heart and Vascular Institute',
    yearsOfPractice: 12,
    details: 'Specializes in cardiac imaging and non-invasive cardiology.',
  },
  {
    name: 'Dr. Abigail Scott',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: "",
    consultationCharge: 205,
    hospital: 'Premier Heart Clinic',
    yearsOfPractice: 18,
    details: 'Focuses on preventive cardiology and lipid management.',
  },
  {
    name: 'Dr. Henry Collins',
    specialty: 'Cardiologist',
    rating: 4.7,
    image: "",
    consultationCharge: 190,
    hospital: 'Noble Heart Care Center',
    yearsOfPractice: 14,
    details: 'Expert in coronary artery disease and stent placements.',
  },
  {
    name: 'Dr. Grace Turner',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: "",
    consultationCharge: 175,
    hospital: 'Heartbeat Health Clinic',
    yearsOfPractice: 11,
    details: 'Specializes in women’s heart health and preventive cardiology.',
  },
  {
    name: 'Dr. Logan Bennett',
    specialty: 'Cardiologist',
    rating: 4.6,
    image: "",
    consultationCharge: 185,
    hospital: 'Cardio Excellence Clinic',
    yearsOfPractice: 15,
    details: 'Expert in interventional cardiology and vascular disease treatments.',
  },
  {
    name: 'Dr. Lily Mitchell',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: "",
    consultationCharge: 210,
    hospital: 'Elite Heart Care',
    yearsOfPractice: 19,
    details: 'Specializes in electrophysiology, pacemaker, and defibrillator implants.',
  },
  {
    name: 'Dr. Jack Ramirez',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: "",
    consultationCharge: 200,
    hospital: 'Heart Specialists Group',
    yearsOfPractice: 17,
    details: 'Focuses on complex cardiac conditions and advanced imaging techniques.',
  },
  {
    name: 'Dr. Ella Gray',
    specialty: 'Cardiologist',
    rating: 4.7,
    image: "",
    consultationCharge: 195,
    hospital: 'Pinnacle Cardiology Clinic',
    yearsOfPractice: 13,
    details: 'Expert in congestive heart failure and cardiomyopathies.',
  },  
  {
    name: 'Dr. Isabella Garcia',
    specialty: 'Dermatologist',
    rating: 4.9,
    image: "",
    consultationCharge: 150,
    hospital: 'Skin Care Clinic',
    yearsOfPractice: 12,
    details: 'Specializes in acne treatment and cosmetic dermatology.',
  },
  {
    name: 'Dr. Liam Wilson',
    specialty: 'Dermatologist',
    rating: 4.8,
    image: "",
    consultationCharge: 140,
    hospital: 'Clear Skin Center',
    yearsOfPractice: 10,
    details: 'Expert in treating eczema, psoriasis, and skin cancer screening.',
  },
  {
    name: 'Dr. Sophia Evans',
    specialty: 'Dermatologist',
    rating: 4.7,
    image: "",
    consultationCharge: 160,
    hospital: 'Glow Skin Care',
    yearsOfPractice: 13,
    details: 'Focuses on laser treatments and anti-aging skincare solutions.',
  },
  {
    name: 'Dr. Noah Anderson',
    specialty: 'Dermatologist',
    rating: 4.9,
    image: "",
    consultationCharge: 145,
    hospital: 'Derma Experts Clinic',
    yearsOfPractice: 11,
    details: 'Specializes in surgical dermatology and mole removal.',
  },
  {
    name: 'Dr. Mia Johnson',
    specialty: 'Dermatologist',
    rating: 4.6,
    image: "",
    consultationCharge: 155,
    hospital: 'Youthful Skin Clinic',
    yearsOfPractice: 14,
    details: 'Expert in skin rejuvenation, chemical peels, and botox treatments.',
  },
  {
    name: 'Dr. Ethan Brown',
    specialty: 'Dermatologist',
    rating: 4.8,
    image: "",
    consultationCharge: 170,
    hospital: 'Perfect Skin Center',
    yearsOfPractice: 9,
    details: 'Specializes in hair loss treatments and scalp care.',
  },
  {
    name: 'Dr. Emily Martinez',
    specialty: 'Dermatologist',
    rating: 4.7,
    image: "",
    consultationCharge: 165,
    hospital: 'Radiance Dermatology',
    yearsOfPractice: 15,
    details: 'Focuses on laser skin resurfacing and advanced acne treatments.',
  },
  {
    name: 'Dr. James Hernandez',
    specialty: 'Dermatologist',
    rating: 4.9,
    image: "",
    consultationCharge: 155,
    hospital: 'Dermacare Specialists',
    yearsOfPractice: 18,
    details: 'Expert in skin cancer treatments and advanced dermatologic surgery.',
  },
  {
    name: 'Dr. Grace Taylor',
    specialty: 'Dermatologist',
    rating: 4.6,
    image: "",
    consultationCharge: 160,
    hospital: 'Skin Health Institute',
    yearsOfPractice: 12,
    details: 'Specializes in skin hydration therapy and scar treatment.',
  },
  {
    name: 'Dr. Benjamin Clark',
    specialty: 'Dermatologist',
    rating: 4.8,
    image: "",
    consultationCharge: 170,
    hospital: 'Advanced Skin Care Clinic',
    yearsOfPractice: 14,
    details: 'Focuses on treating severe acne and rosacea.',
  },
  {
    name: 'Dr. Amelia Lewis',
    specialty: 'Dermatologist',
    rating: 4.7,
    image: "",
    consultationCharge: 160,
    hospital: 'The Skin Clinic',
    yearsOfPractice: 11,
    details: 'Expert in cosmetic dermatology and chemical peel treatments.',
  },
  {
    name: 'Dr. Mason White',
    specialty: 'Dermatologist',
    rating: 4.9,
    image: "",
    consultationCharge: 150,
    hospital: 'SkinCare Innovations',
    yearsOfPractice: 13,
    details: 'Specializes in treating autoimmune skin disorders and vitiligo.',
  },
  {
    name: 'Dr. Ella Davis',
    specialty: 'Dermatologist',
    rating: 4.8,
    image: "",
    consultationCharge: 145,
    hospital: 'SkinMed Clinic',
    yearsOfPractice: 10,
    details: 'Focuses on laser hair removal and scar revision surgeries.',
  },
  {
    name: 'Dr. Logan Thompson',
    specialty: 'Dermatologist',
    rating: 4.7,
    image: "",
    consultationCharge: 160,
    hospital: 'Smooth Skin Clinic',
    yearsOfPractice: 16,
    details: 'Expert in managing chronic skin diseases like psoriasis and eczema.',
  },
  {
    name: 'Dr. Ava Martinez',
    specialty: 'Dermatologist',
    rating: 4.9,
    image: "",
    consultationCharge: 155,
    hospital: 'Flawless Skin Center',
    yearsOfPractice: 17,
    details: 'Specializes in skin cancer prevention and mole mapping.',
  },
  {
    name: 'Dr. Henry Robinson',
    specialty: 'Dermatologist',
    rating: 4.8,
    image: "",
    consultationCharge: 170,
    hospital: 'Skin Solutions Clinic',
    yearsOfPractice: 15,
    details: 'Focuses on pediatric dermatology and rare skin conditions.',
  },
  {
    name: 'Dr. Chloe Lopez',
    specialty: 'Dermatologist',
    rating: 4.7,
    image: "",
    consultationCharge: 145,
    hospital: 'Glow Dermatology Clinic',
    yearsOfPractice: 14,
    details: 'Expert in cosmetic procedures and non-invasive skin treatments.',
  },
  {
    name: 'Dr. Jack Hill',
    specialty: 'Dermatologist',
    rating: 4.9,
    image: "",
    consultationCharge: 165,
    hospital: 'Elite Skin Care',
    yearsOfPractice: 19,
    details: 'Specializes in melasma treatments and advanced skin diagnostics.',
  },
  {
    name: 'Dr. Lily Harris',
    specialty: 'Dermatologist',
    rating: 4.8,
    image: "",
    consultationCharge: 160,
    hospital: 'Derma Glow Clinic',
    yearsOfPractice: 12,
    details: 'Focuses on laser treatments, fillers, and anti-aging skincare.',
  },
  {
    name: 'Dr. Alexander King',
    specialty: 'Dermatologist',
    rating: 4.7,
    image: "",
    consultationCharge: 150,
    hospital: 'Perfect Skin Care Center',
    yearsOfPractice: 13,
    details: 'Expert in treating skin pigmentation disorders and keloid scars.',
  },
  {
    name: 'Dr. Oliver Thompson',
    specialty: 'Neurologist',
    rating: 4.8,
    image: "",
    consultationCharge: 200,
    hospital: 'Neuro Health Clinic',
    yearsOfPractice: 15,
    details: 'Expert in treating migraines, seizures, and multiple sclerosis.',
  },
  {
    name: 'Dr. Ava Martinez',
    specialty: 'Neurologist',
    rating: 4.7,
    image: "",
    consultationCharge: 210,
    hospital: 'Advanced Brain Care',
    yearsOfPractice: 12,
    details: 'Specializes in stroke rehabilitation and movement disorders.',
  },
  {
    name: 'Dr. William Taylor',
    specialty: 'Neurologist',
    rating: 4.9,
    image: "",
    consultationCharge: 220,
    hospital: 'Brain Wellness Center',
    yearsOfPractice: 18,
    details: 'Focuses on neurodegenerative diseases like Parkinson\'s and Alzheimer\'s.',
  },
  {
    name: 'Dr. Sophia White',
    specialty: 'Neurologist',
    rating: 4.8,
    image: "",
    consultationCharge: 190,
    hospital: 'Neurology Excellence Clinic',
    yearsOfPractice: 11,
    details: 'Expert in treating epilepsy and sleep disorders.',
  },
  {
    name: 'Dr. James Anderson',
    specialty: 'Neurologist',
    rating: 4.7,
    image: "",
    consultationCharge: 215,
    hospital: 'Brain & Spine Care',
    yearsOfPractice: 16,
    details: 'Specializes in headaches, neuropathy, and neuroimmunology.',
  },
  {
    name: 'Dr. Emily Clark',
    specialty: 'Neurologist',
    rating: 4.9,
    image: "",
    consultationCharge: 230,
    hospital: 'Neuro Diagnostic Clinic',
    yearsOfPractice: 17,
    details: 'Focuses on neuroinfections, nerve injuries, and spinal cord disorders.',
  },
  {
    name: 'Dr. Henry Lewis',
    specialty: 'Neurologist',
    rating: 4.8,
    image: "",
    consultationCharge: 205,
    hospital: 'Neuro Health Specialists',
    yearsOfPractice: 14,
    details: 'Expert in stroke prevention and management of traumatic brain injuries.',
  },
  {
    name: 'Dr. Mia Rodriguez',
    specialty: 'Neurologist',
    rating: 4.7,
    image: "",
    consultationCharge: 195,
    hospital: 'Brain & Nerve Clinic',
    yearsOfPractice: 10,
    details: 'Specializes in dementia care and cognitive impairments.',
  },
  {
    name: 'Dr. Benjamin Harris',
    specialty: 'Neurologist',
    rating: 4.9,
    image: "",
    consultationCharge: 225,
    hospital: 'Neurotherapy Center',
    yearsOfPractice: 20,
    details: 'Focuses on treating epilepsy, tremors, and ALS.',
  },
  {
    name: 'Dr. Isabella Perez',
    specialty: 'Neurologist',
    rating: 4.8,
    image: "",
    consultationCharge: 210,
    hospital: 'Brain Science Institute',
    yearsOfPractice: 13,
    details: 'Expert in treating vertigo, headaches, and neurological pain.',
  },
  {
    name: 'Dr. Lucas Lee',
    specialty: 'Neurologist',
    rating: 4.7,
    image: "",
    consultationCharge: 220,
    hospital: 'NeuroMind Clinic',
    yearsOfPractice: 17,
    details: 'Specializes in peripheral neuropathy and muscle disorders.',
  },
  {
    name: 'Dr. Charlotte King',
    specialty: 'Neurologist',
    rating: 4.8,
    image: "",
    consultationCharge: 205,
    hospital: 'Brain & Nervous System Center',
    yearsOfPractice: 15,
    details: 'Focuses on treating brain tumors, spinal disorders, and MS.',
  },
  {
    name: 'Dr. Elijah Walker',
    specialty: 'Neurologist',
    rating: 4.9,
    image: "",
    consultationCharge: 230,
    hospital: 'Comprehensive Neurocare',
    yearsOfPractice: 19,
    details: 'Expert in neurocritical care and sleep neurology.',
  },
  {
    name: 'Dr. Grace Johnson',
    specialty: 'Neurologist',
    rating: 4.7,
    image: "",
    consultationCharge: 200,
    hospital: 'Neurology & Brain Disorders Clinic',
    yearsOfPractice: 12,
    details: 'Specializes in epilepsy treatment and neurodiagnostic tests.',
  },
  {
    name: 'Dr. Samuel Martinez',
    specialty: 'Neurologist',
    rating: 4.8,
    image: "",
    consultationCharge: 215,
    hospital: 'Brainwave Medical Center',
    yearsOfPractice: 16,
    details: 'Focuses on movement disorders and neuromuscular conditions.',
  },
  {
    name: 'Dr. Ella Evans',
    specialty: 'Neurologist',
    rating: 4.9,
    image: "",
    consultationCharge: 225,
    hospital: 'Mind & Brain Care Clinic',
    yearsOfPractice: 18,
    details: 'Expert in neuro-oncology and stroke rehabilitation.',
  },
  {
    name: 'Dr. Matthew Brown',
    specialty: 'Neurologist',
    rating: 4.7,
    image: "",
    consultationCharge: 205,
    hospital: 'Neurology Research Center',
    yearsOfPractice: 14,
    details: 'Specializes in diagnosing and treating complex neurological disorders.',
  },
  {
    name: 'Dr. Harper Davis',
    specialty: 'Neurologist',
    rating: 4.8,
    image: "",
    consultationCharge: 200,
    hospital: 'NeuroCare Clinic',
    yearsOfPractice: 13,
    details: 'Focuses on neurosurgery, headaches, and spinal cord issues.',
  },
  {
    name: 'Dr. Ethan Clark',
    specialty: 'Neurologist',
    rating: 4.9,
    image: "",
    consultationCharge: 230,
    hospital: 'Advanced Neurology Center',
    yearsOfPractice: 19,
    details: 'Expert in neuromuscular disorders and advanced neuroimaging.',
  },
  {
    name: 'Dr. Lily Gonzalez',
    specialty: 'Neurologist',
    rating: 4.7,
    image: "",
    consultationCharge: 190,
    hospital: 'Brain Function Center',
    yearsOfPractice: 11,
    details: 'Specializes in multiple sclerosis and balance disorders.',
  },
  {
    name: 'Dr. Amelia Harris',
    specialty: 'Pediatrician',
    rating: 4.9,
    image: "",
    consultationCharge: 150,
    hospital: 'Children\'s Care Center',
    yearsOfPractice: 10,
    details: 'Specializes in childhood development and early intervention.',
  },
  {
    name: 'Dr. Liam Johnson',
    specialty: 'Pediatrician',
    rating: 4.8,
    image: "",
    consultationCharge: 140,
    hospital: 'Healthy Kids Clinic',
    yearsOfPractice: 12,
    details: 'Expert in pediatric nutrition and infectious diseases.',
  },
  {
    name: 'Dr. Olivia Brown',
    specialty: 'Pediatrician',
    rating: 4.7,
    image: "",
    consultationCharge: 160,
    hospital: 'Pediatric Wellness Clinic',
    yearsOfPractice: 8,
    details: 'Focuses on asthma care and childhood allergies.',
  },
  {
    name: 'Dr. Noah Williams',
    specialty: 'Pediatrician',
    rating: 4.9,
    image: "",
    consultationCharge: 155,
    hospital: 'Bright Futures Pediatrics',
    yearsOfPractice: 9,
    details: 'Specializes in newborn care and preventive medicine.',
  },
  {
    name: 'Dr. Charlotte Davis',
    specialty: 'Pediatrician',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Kids Health Specialists',
    yearsOfPractice: 11,
    details: 'Expert in childhood immunization and growth monitoring.',
  },
  {
    name: 'Dr. Mason Martinez',
    specialty: 'Pediatrician',
    rating: 4.7,
    image: "",
    consultationCharge: 145,
    hospital: 'Little Smiles Pediatric Clinic',
    yearsOfPractice: 13,
    details: 'Focuses on childhood obesity and respiratory diseases.',
  },
  {
    name: 'Dr. Sophia Garcia',
    specialty: 'Pediatrician',
    rating: 4.9,
    image: "",
    consultationCharge: 160,
    hospital: 'Care & Comfort Pediatrics',
    yearsOfPractice: 14,
    details: 'Specializes in treating ADHD and developmental delays.',
  },
  {
    name: 'Dr. Ethan Lee',
    specialty: 'Pediatrician',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Happy Kids Clinic',
    yearsOfPractice: 10,
    details: 'Expert in treating childhood infections and chronic conditions.',
  },
  {
    name: 'Dr. Mia White',
    specialty: 'Pediatrician',
    rating: 4.9,
    image: "",
    consultationCharge: 155,
    hospital: 'Bright Beginnings Pediatrics',
    yearsOfPractice: 12,
    details: 'Focuses on pediatric dermatology and skin infections.',
  },
  {
    name: 'Dr. Lucas Clark',
    specialty: 'Pediatrician',
    rating: 4.7,
    image: "",
    consultationCharge: 145,
    hospital: 'Sunshine Pediatric Care',
    yearsOfPractice: 11,
    details: 'Specializes in pediatric cardiology and genetic disorders.',
  },
  {
    name: 'Dr. Emma Taylor',
    specialty: 'Pediatrician',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Happy Hearts Pediatrics',
    yearsOfPractice: 13,
    details: 'Expert in newborn screening and child vaccinations.',
  },
  {
    name: 'Dr. Henry King',
    specialty: 'Pediatrician',
    rating: 4.9,
    image: "",
    consultationCharge: 160,
    hospital: 'Pediatric Health Institute',
    yearsOfPractice: 15,
    details: 'Focuses on chronic illness management and well-child visits.',
  },
  {
    name: 'Dr. Abigail Rodriguez',
    specialty: 'Pediatrician',
    rating: 4.7,
    image: "",
    consultationCharge: 145,
    hospital: 'Healthy Steps Pediatrics',
    yearsOfPractice: 10,
    details: 'Specializes in neonatal care and early child development.',
  },
  {
    name: 'Dr. Alexander Thompson',
    specialty: 'Pediatrician',
    rating: 4.8,
    image: "",
    consultationCharge: 155,
    hospital: 'Care for Kids Clinic',
    yearsOfPractice: 14,
    details: 'Expert in managing childhood asthma and diabetes.',
  },
  {
    name: 'Dr. Ella Johnson',
    specialty: 'Pediatrician',
    rating: 4.9,
    image: "",
    consultationCharge: 160,
    hospital: 'Young Hearts Pediatrics',
    yearsOfPractice: 9,
    details: 'Focuses on childhood neurological development and speech therapy.',
  },
  {
    name: 'Dr. Daniel Hernandez',
    specialty: 'Pediatrician',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Children First Pediatrics',
    yearsOfPractice: 13,
    details: 'Specializes in pediatric allergy and immunology.',
  },
  {
    name: 'Dr. Chloe Adams',
    specialty: 'Pediatrician',
    rating: 4.7,
    image: "",
    consultationCharge: 145,
    hospital: 'Bright Futures Clinic',
    yearsOfPractice: 11,
    details: 'Expert in developmental pediatrics and behavioral health.',
  },
  {
    name: 'Dr. Matthew Perez',
    specialty: 'Pediatrician',
    rating: 4.9,
    image: "",
    consultationCharge: 160,
    hospital: 'Growing Smiles Pediatric Care',
    yearsOfPractice: 12,
    details: 'Focuses on pediatric emergency medicine and urgent care.',
  },
  {
    name: 'Dr. Avery Lewis',
    specialty: 'Pediatrician',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Future Health Pediatrics',
    yearsOfPractice: 8,
    details: 'Specializes in newborn care and family education.',
  },
  {
    name: 'Dr. Grace Ramirez',
    specialty: 'Pediatrician',
    rating: 4.7,
    image: "",
    consultationCharge: 145,
    hospital: 'Bright Minds Pediatric Clinic',
    yearsOfPractice: 10,
    details: 'Expert in childhood growth disorders and metabolic diseases.',
  },
  {
    name: 'Dr. William Scott',
    specialty: 'Orthopedic Surgeon',
    rating: 4.9,
    image: "",
    consultationCharge: 180,
    hospital: 'Advanced Orthopedic Center',
    yearsOfPractice: 15,
    details: 'Expert in joint replacement surgeries and sports injuries.',
  },
  {
    name: 'Dr. Emily Anderson',
    specialty: 'Orthopedic Surgeon',
    rating: 4.8,
    image: "",
    consultationCharge: 170,
    hospital: 'Bone & Joint Specialists',
    yearsOfPractice: 12,
    details: 'Specializes in minimally invasive spine surgeries.',
  },
  {
    name: 'Dr. Michael Evans',
    specialty: 'Orthopedic Surgeon',
    rating: 4.7,
    image: "",
    consultationCharge: 185,
    hospital: 'OrthoCare Clinic',
    yearsOfPractice: 14,
    details: 'Focuses on treating complex fractures and dislocations.',
  },
  {
    name: 'Dr. Sophia Martinez',
    specialty: 'Orthopedic Surgeon',
    rating: 4.9,
    image: "",
    consultationCharge: 175,
    hospital: 'Joint Health Clinic',
    yearsOfPractice: 16,
    details: 'Specializes in knee and hip replacement surgeries.',
  },
  {
    name: 'Dr. Benjamin Lewis',
    specialty: 'Orthopedic Surgeon',
    rating: 4.8,
    image: "",
    consultationCharge: 190,
    hospital: 'Total Bone & Joint Institute',
    yearsOfPractice: 18,
    details: 'Expert in shoulder arthroscopy and ACL reconstruction.',
  },
  {
    name: 'Dr. Grace Foster',
    specialty: 'Orthopedic Surgeon',
    rating: 4.7,
    image: "",
    consultationCharge: 170,
    hospital: 'Premier Orthopedic Care',
    yearsOfPractice: 11,
    details: 'Focuses on treating arthritis and degenerative joint conditions.',
  },
  {
    name: 'Dr. Daniel Harris',
    specialty: 'Orthopedic Surgeon',
    rating: 4.9,
    image: "",
    consultationCharge: 185,
    hospital: 'Joint Replacement Specialists',
    yearsOfPractice: 13,
    details: 'Expert in complex knee surgeries and cartilage repair.',
  },
  {
    name: 'Dr. Ava Rivera',
    specialty: 'Orthopedic Surgeon',
    rating: 4.8,
    image: "",
    consultationCharge: 175,
    hospital: 'Orthopedic Solutions Clinic',
    yearsOfPractice: 14,
    details: 'Specializes in treating pediatric orthopedic conditions.',
  },
  {
    name: 'Dr. James Hall',
    specialty: 'Orthopedic Surgeon',
    rating: 4.7,
    image: "",
    consultationCharge: 180,
    hospital: 'Elite Ortho Care',
    yearsOfPractice: 12,
    details: 'Focuses on hand and wrist surgeries, including carpal tunnel.',
  },
  {
    name: 'Dr. Isabella Robinson',
    specialty: 'Orthopedic Surgeon',
    rating: 4.9,
    image: "",
    consultationCharge: 190,
    hospital: 'Spine & Joint Specialists',
    yearsOfPractice: 15,
    details: 'Expert in spine surgeries and scoliosis treatment.',
  },
  {
    name: 'Dr. Elijah Wright',
    specialty: 'Orthopedic Surgeon',
    rating: 4.8,
    image: "",
    consultationCharge: 180,
    hospital: 'Ortho Elite Clinic',
    yearsOfPractice: 17,
    details: 'Specializes in hip and shoulder joint replacements.',
  },
  {
    name: 'Dr. Mia Walker',
    specialty: 'Orthopedic Surgeon',
    rating: 4.7,
    image: "",
    consultationCharge: 170,
    hospital: 'Advanced Joint Care Clinic',
    yearsOfPractice: 10,
    details: 'Focuses on sports injuries and ligament reconstruction.',
  },
  {
    name: 'Dr. Oliver Young',
    specialty: 'Orthopedic Surgeon',
    rating: 4.9,
    image: "",
    consultationCharge: 190,
    hospital: 'Ortho Excellence Clinic',
    yearsOfPractice: 16,
    details: 'Expert in complex trauma surgeries and fracture management.',
  },
  {
    name: 'Dr. Evelyn Torres',
    specialty: 'Orthopedic Surgeon',
    rating: 4.8,
    image: "",
    consultationCharge: 185,
    hospital: 'Joint Recovery Specialists',
    yearsOfPractice: 13,
    details: 'Specializes in joint reconstruction and sports medicine.',
  },
  {
    name: 'Dr. Jackson Green',
    specialty: 'Orthopedic Surgeon',
    rating: 4.7,
    image: "",
    consultationCharge: 180,
    hospital: 'Comprehensive Orthopedic Center',
    yearsOfPractice: 14,
    details: 'Focuses on foot and ankle surgeries and joint deformities.',
  },
  {
    name: 'Dr. Aria Scott',
    specialty: 'Orthopedic Surgeon',
    rating: 4.9,
    image: "",
    consultationCharge: 195,
    hospital: 'Pinnacle Orthopedics',
    yearsOfPractice: 18,
    details: 'Expert in arthroscopic surgery and joint preservation.',
  },
  {
    name: 'Dr. Henry Clark',
    specialty: 'Orthopedic Surgeon',
    rating: 4.8,
    image: "",
    consultationCharge: 175,
    hospital: 'Elite Spine & Joint Care',
    yearsOfPractice: 15,
    details: 'Specializes in spinal fusion and scoliosis correction.',
  },
  {
    name: 'Dr. Lily Perez',
    specialty: 'Orthopedic Surgeon',
    rating: 4.7,
    image: "",
    consultationCharge: 170,
    hospital: 'OrthoAdvanced Clinic',
    yearsOfPractice: 12,
    details: 'Focuses on knee reconstruction and orthopedic trauma.',
  },
  {
    name: 'Dr. Lucas King',
    specialty: 'Orthopedic Surgeon',
    rating: 4.9,
    image: "",
    consultationCharge: 185,
    hospital: 'Joint Preservation Specialists',
    yearsOfPractice: 16,
    details: 'Expert in joint arthroscopy and shoulder reconstructions.',
  },
  {
    name: 'Dr. Harper Ramirez',
    specialty: 'Orthopedic Surgeon',
    rating: 4.8,
    image: "",
    consultationCharge: 180,
    hospital: 'Premier Ortho Care Center',
    yearsOfPractice: 11,
    details: 'Specializes in pediatric orthopedic surgeries and trauma care.',
  },
  {
    name: 'Dr. Samuel Mitchell',
    specialty: 'Ophthalmologist',
    rating: 4.9,
    image: "",
    consultationCharge: 150,
    hospital: 'Vision Care Center',
    yearsOfPractice: 14,
    details: 'Specializes in cataract surgery and laser vision correction.',
  },
  {
    name: 'Dr. Isabella Brown',
    specialty: 'Ophthalmologist',
    rating: 4.8,
    image: "",
    consultationCharge: 140,
    hospital: 'Eye Health Clinic',
    yearsOfPractice: 12,
    details: 'Expert in treating glaucoma and diabetic eye diseases.',
  },
  {
    name: 'Dr. Elijah Johnson',
    specialty: 'Ophthalmologist',
    rating: 4.7,
    image: "",
    consultationCharge: 160,
    hospital: 'Clear Sight Institute',
    yearsOfPractice: 15,
    details: 'Focuses on pediatric ophthalmology and eye disorders.',
  },
  {
    name: 'Dr. Mia Davis',
    specialty: 'Ophthalmologist',
    rating: 4.9,
    image: "",
    consultationCharge: 155,
    hospital: 'Advanced Eye Care',
    yearsOfPractice: 16,
    details: 'Specializes in corneal transplants and refractive surgery.',
  },
  {
    name: 'Dr. Benjamin Taylor',
    specialty: 'Ophthalmologist',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Optimum Vision Clinic',
    yearsOfPractice: 11,
    details: 'Expert in treating retinal diseases and macular degeneration.',
  },
  {
    name: 'Dr. Charlotte Wilson',
    specialty: 'Ophthalmologist',
    rating: 4.7,
    image: "",
    consultationCharge: 145,
    hospital: 'Eye Surgery Center',
    yearsOfPractice: 13,
    details: 'Focuses on eyelid surgery and cosmetic procedures.',
  },
  {
    name: 'Dr. Oliver Anderson',
    specialty: 'Ophthalmologist',
    rating: 4.9,
    image: "",
    consultationCharge: 160,
    hospital: 'Vision Plus Hospital',
    yearsOfPractice: 14,
    details: 'Specializes in laser eye treatments and eye exams.',
  },
  {
    name: 'Dr. Amelia Thomas',
    specialty: 'Ophthalmologist',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Comprehensive Eye Care',
    yearsOfPractice: 12,
    details: 'Expert in cataract and lens replacement surgeries.',
  },
  {
    name: 'Dr. Henry Martin',
    specialty: 'Ophthalmologist',
    rating: 4.7,
    image: "",
    consultationCharge: 155,
    hospital: 'Healthy Eyes Clinic',
    yearsOfPractice: 10,
    details: 'Focuses on treating eye infections and inflammations.',
  },
  {
    name: 'Dr. Evelyn White',
    specialty: 'Ophthalmologist',
    rating: 4.9,
    image: "",
    consultationCharge: 165,
    hospital: 'Vision Health Center',
    yearsOfPractice: 15,
    details: 'Specializes in ocular surgery and vision rehabilitation.',
  },
  {
    name: 'Dr. Lucas Harris',
    specialty: 'Ophthalmologist',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Eye Care Specialists',
    yearsOfPractice: 14,
    details: 'Expert in diabetic retinopathy and laser treatments.',
  },
  {
    name: 'Dr. Aria Walker',
    specialty: 'Ophthalmologist',
    rating: 4.7,
    image: "",
    consultationCharge: 140,
    hospital: 'Advanced Vision Clinic',
    yearsOfPractice: 13,
    details: "Focuses on vision therapy and children's eye care.",
  },
  {
    name: 'Dr. Jacob Hall',
    specialty: 'Ophthalmologist',
    rating: 4.9,
    image: "",
    consultationCharge: 160,
    hospital: 'Eye Institute',
    yearsOfPractice: 16,
    details: 'Specializes in comprehensive eye exams and diagnostics.',
  },
  {
    name: 'Dr. Lily Young',
    specialty: 'Ophthalmologist',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Elite Eye Care',
    yearsOfPractice: 12,
    details: 'Expert in treating ocular allergies and dry eyes.',
  },
  {
    name: 'Dr. Jackson King',
    specialty: 'Ophthalmologist',
    rating: 4.7,
    image: "",
    consultationCharge: 155,
    hospital: 'Visionary Eye Clinic',
    yearsOfPractice: 11,
    details: 'Focuses on keratoconus treatment and contact lens fittings.',
  },
  {
    name: 'Dr. Scarlett Lee',
    specialty: 'Ophthalmologist',
    rating: 4.9,
    image: "",
    consultationCharge: 165,
    hospital: 'Family Eye Care Center',
    yearsOfPractice: 18,
    details: 'Specializes in glaucoma management and surgical treatments.',
  },
  {
    name: 'Dr. Nathaniel Clark',
    specialty: 'Ophthalmologist',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Community Eye Clinic',
    yearsOfPractice: 14,
    details: 'Expert in treating vision disorders and eye injuries.',
  },
  {
    name: 'Dr. Grace Robinson',
    specialty: 'Ophthalmologist',
    rating: 4.7,
    image: "",
    consultationCharge: 140,
    hospital: 'Premier Eye Specialists',
    yearsOfPractice: 10,
    details: 'Focuses on pediatric eye care and visual development.',
  },
  {
    name: 'Dr. Sarah Mitchell',
    specialty: 'Psychiatrist',
    rating: 4.9,
    image: "",
    consultationCharge: 120,
    hospital: 'Mind Care Institute',
    yearsOfPractice: 10,
    details: 'Specializes in cognitive behavioral therapy and mood disorders.',
  },
  {
    name: 'Dr. Michael Johnson',
    specialty: 'Psychiatrist',
    rating: 4.8,
    image: "",
    consultationCharge: 130,
    hospital: 'Mental Wellness Center',
    yearsOfPractice: 12,
    details: 'Expert in anxiety disorders and trauma therapy.',
  },
  {
    name: 'Dr. Emily Davis',
    specialty: 'Psychiatrist',
    rating: 4.7,
    image: "",
    consultationCharge: 125,
    hospital: 'Harmony Mental Health',
    yearsOfPractice: 15,
    details: 'Focuses on depression and family therapy.',
  },
  {
    name: 'Dr. Joshua Smith',
    specialty: 'Psychiatrist',
    rating: 4.9,
    image: "",
    consultationCharge: 140,
    hospital: 'Caring Minds Clinic',
    yearsOfPractice: 8,
    details: 'Specializes in adolescent psychiatry and developmental disorders.',
  },
  {
    name: 'Dr. Olivia Brown',
    specialty: 'Psychiatrist',
    rating: 4.8,
    image: "",
    consultationCharge: 135,
    hospital: 'Insight Therapy Center',
    yearsOfPractice: 14,
    details: 'Expert in psychopharmacology and mood stabilization.',
  },
  {
    name: 'Dr. Aiden Taylor',
    specialty: 'Psychiatrist',
    rating: 4.7,
    image: "",
    consultationCharge: 130,
    hospital: 'New Horizons Mental Health',
    yearsOfPractice: 11,
    details: 'Focuses on adult psychiatry and emotional disorders.',
  },
  {
    name: 'Dr. Sophia Wilson',
    specialty: 'Psychiatrist',
    rating: 4.9,
    image: "",
    consultationCharge: 145,
    hospital: 'Tranquil Minds Clinic',
    yearsOfPractice: 13,
    details: 'Specializes in PTSD and trauma recovery.',
  },
  {
    name: 'Dr. Ethan Lee',
    specialty: 'Psychiatrist',
    rating: 4.8,
    image: "",
    consultationCharge: 120,
    hospital: 'Serenity Wellness Center',
    yearsOfPractice: 9,
    details: 'Expert in behavioral therapy and crisis intervention.',
  },
  {
    name: 'Dr. Mia Garcia',
    specialty: 'Psychiatrist',
    rating: 4.7,
    image: "",
    consultationCharge: 125,
    hospital: 'Mindful Care Clinic',
    yearsOfPractice: 10,
    details: 'Focuses on stress management and coping strategies.',
  },
  {
    name: 'Dr. Liam Martinez',
    specialty: 'Psychiatrist',
    rating: 4.9,
    image: "",
    consultationCharge: 150,
    hospital: 'Balance Mental Health',
    yearsOfPractice: 16,
    details: 'Specializes in psychotic disorders and rehabilitation.',
  },
  {
    name: 'Dr. Amelia Anderson',
    specialty: 'Psychiatrist',
    rating: 4.8,
    image: "",
    consultationCharge: 140,
    hospital: 'Hope Therapy Center',
    yearsOfPractice: 12,
    details: 'Expert in depression and emotional healing.',
  },
  {
    name: 'Dr. Lucas Robinson',
    specialty: 'Psychiatrist',
    rating: 4.7,
    image: "",
    consultationCharge: 135,
    hospital: 'Clear Mind Clinic',
    yearsOfPractice: 10,
    details: 'Focuses on anxiety disorders and counseling.',
  },
  {
    name: 'Dr. Harper Clark',
    specialty: 'Psychiatrist',
    rating: 4.9,
    image: "",
    consultationCharge: 145,
    hospital: 'Mental Health Partners',
    yearsOfPractice: 15,
    details: 'Specializes in family therapy and interpersonal issues.',
  },
  {
    name: 'Dr. Benjamin Young',
    specialty: 'Psychiatrist',
    rating: 4.8,
    image: "",
    consultationCharge: 150,
    hospital: 'Mind Oasis Center',
    yearsOfPractice: 14,
    details: 'Expert in cognitive therapy and self-improvement strategies.',
  },
  {
    name: 'Dr. Evelyn King',
    specialty: 'Psychiatrist',
    rating: 4.7,
    image: "",
    consultationCharge: 130,
    hospital: 'Restoration Mental Health',
    yearsOfPractice: 11,
    details: 'Focuses on holistic approaches to mental wellness.',
  },
  {
    name: 'Dr. Noah Hall',
    specialty: 'Psychiatrist',
    rating: 4.9,
    image: "",
    consultationCharge: 155,
    hospital: 'Healing Minds Institute',
    yearsOfPractice: 18,
    details: 'Specializes in community mental health and outreach programs.',
  },
  {
    name: 'Dr. Scarlett Gonzalez',
    specialty: 'Psychiatrist',
    rating: 4.8,
    image: "",
    consultationCharge: 140,
    hospital: 'Pathways Mental Health',
    yearsOfPractice: 12,
    details: 'Expert in emotional wellness and crisis management.',
  },
  {
    name: 'Dr. Lucas Adams',
    specialty: 'Psychiatrist',
    rating: 4.7,
    image: "",
    consultationCharge: 125,
    hospital: 'Mind & Soul Center',
    yearsOfPractice: 10,
    details: 'Focuses on addiction recovery and support.',
  },
  {
    name: 'Dr. Jennifer Williams',
    specialty: 'Endocrinologist',
    rating: 4.9,
    image: "",
    consultationCharge: 130,
    hospital: 'Hormone Health Center',
    yearsOfPractice: 12,
    details: 'Expert in diabetes management and thyroid disorders.',
  },
  {
    name: 'Dr. Daniel Martinez',
    specialty: 'Endocrinologist',
    rating: 4.8,
    image: "",
    consultationCharge: 135,
    hospital: 'Metabolic Health Clinic',
    yearsOfPractice: 14,
    details: 'Specializes in obesity and metabolic syndrome.',
  },
  {
    name: 'Dr. Mia Rodriguez',
    specialty: 'Endocrinologist',
    rating: 4.7,
    image: "",
    consultationCharge: 120,
    hospital: 'Thyroid Care Institute',
    yearsOfPractice: 11,
    details: 'Focuses on adrenal and pituitary disorders.',
  },
  {
    name: 'Dr. Joseph Taylor',
    specialty: 'Endocrinologist',
    rating: 4.9,
    image: "",
    consultationCharge: 140,
    hospital: 'Balanced Hormones Clinic',
    yearsOfPractice: 15,
    details: 'Expert in hormone replacement therapy.',
  },
  {
    name: 'Dr. Sophia Brown',
    specialty: 'Endocrinologist',
    rating: 4.8,
    image: "",
    consultationCharge: 145,
    hospital: 'Diabetes & Endocrinology Center',
    yearsOfPractice: 13,
    details: 'Specializes in insulin resistance and metabolic health.',
  },
  {
    name: 'Dr. Liam Johnson',
    specialty: 'Endocrinologist',
    rating: 4.7,
    image: "",
    consultationCharge: 125,
    hospital: 'Hormone Balance Institute',
    yearsOfPractice: 10,
    details: 'Focuses on reproductive endocrinology.',
  },
  {
    name: 'Dr. Emily Clark',
    specialty: 'Endocrinologist',
    rating: 4.9,
    image: "",
    consultationCharge: 135,
    hospital: 'Metabolism & Hormone Clinic',
    yearsOfPractice: 12,
    details: 'Expert in diabetes education and prevention.',
  },
  {
    name: 'Dr. Noah Walker',
    specialty: 'Endocrinologist',
    rating: 4.8,
    image: "",
    consultationCharge: 130,
    hospital: 'Endocrine Wellness Center',
    yearsOfPractice: 11,
    details: 'Specializes in pediatric endocrinology.',
  },
  {
    name: 'Dr. Isabella Young',
    specialty: 'Endocrinologist',
    rating: 4.7,
    image: "",
    consultationCharge: 120,
    hospital: 'Hormonal Health Institute',
    yearsOfPractice: 9,
    details: 'Focuses on hormone-related disorders in women.',
  },
  {
    name: 'Dr. Ethan Adams',
    specialty: 'Endocrinologist',
    rating: 4.9,
    image: "",
    consultationCharge: 155,
    hospital: 'Thyroid Specialists Clinic',
    yearsOfPractice: 16,
    details: 'Expert in thyroid surgery and disorders.',
  },
  {
    name: 'Dr. Chloe Lee',
    specialty: 'Endocrinologist',
    rating: 4.8,
    image: "",
    consultationCharge: 145,
    hospital: 'Integrative Hormone Health',
    yearsOfPractice: 14,
    details: 'Specializes in integrative approaches to hormone health.',
  },
  {
    name: 'Dr. Benjamin King',
    specialty: 'Endocrinologist',
    rating: 4.7,
    image: "",
    consultationCharge: 130,
    hospital: 'Diabetes Health Center',
    yearsOfPractice: 11,
    details: 'Focuses on chronic disease management and education.',
  },
  {
    name: 'Dr. Grace Martinez',
    specialty: 'Endocrinologist',
    rating: 4.9,
    image: "",
    consultationCharge: 150,
    hospital: 'Hormonal Balance Center',
    yearsOfPractice: 15,
    details: 'Expert in women’s health and hormone therapy.',
  },
  {
    name: 'Dr. James Garcia',
    specialty: 'Endocrinologist',
    rating: 4.8,
    image: "",
    consultationCharge: 135,
    hospital: 'Thyroid Health Clinic',
    yearsOfPractice: 12,
    details: 'Specializes in endocrine tumors and disorders.',
  },
  {
    name: 'Dr. Victoria Wilson',
    specialty: 'Endocrinologist',
    rating: 4.7,
    image: "",
    consultationCharge: 120,
    hospital: 'Endocrine Institute',
    yearsOfPractice: 10,
    details: 'Focuses on adolescent hormonal disorders.',
  },
  {
    name: 'Dr. Jackson Hall',
    specialty: 'Endocrinologist',
    rating: 4.9,
    image: "",
    consultationCharge: 155,
    hospital: 'Metabolic Wellness Center',
    yearsOfPractice: 18,
    details: 'Expert in lifestyle management and weight loss programs.',
  },
  {
    name: 'Dr. Lily Thompson',
    specialty: 'Endocrinologist',
    rating: 4.8,
    image: "",
    consultationCharge: 140,
    hospital: 'Comprehensive Endocrinology',
    yearsOfPractice: 12,
    details: 'Specializes in hormone-related cancers.',
  },
  {
    name: 'Dr. Wyatt Harris',
    specialty: 'Endocrinologist',
    rating: 4.7,
    image: "",
    consultationCharge: 125,
    hospital: 'Hormonal Disorders Clinic',
    yearsOfPractice: 10,
    details: 'Focuses on chronic conditions and patient education.',
  },
  {
    name: 'Dr. Sarah Johnson',
    specialty: 'Gynecologist',
    rating: 4.9,
    image: "",
    consultationCharge: 120,
    hospital: 'Women’s Health Clinic',
    yearsOfPractice: 10,
    details: 'Specializes in reproductive health and family planning.',
  },
  {
    name: 'Dr. Olivia Smith',
    specialty: 'Gynecologist',
    rating: 4.8,
    image: "",
    consultationCharge: 130,
    hospital: 'Ovarian Health Center',
    yearsOfPractice: 12,
    details: 'Expert in managing menopause and hormone therapy.',
  },
  {
    name: 'Dr. Mia Brown',
    specialty: 'Gynecologist',
    rating: 4.7,
    image: "",
    consultationCharge: 125,
    hospital: 'Reproductive Wellness Institute',
    yearsOfPractice: 11,
    details: 'Focuses on fertility issues and reproductive endocrinology.',
  },
  {
    name: 'Dr. Ava Wilson',
    specialty: 'Gynecologist',
    rating: 4.9,
    image: "",
    consultationCharge: 135,
    hospital: 'Maternal Health Center',
    yearsOfPractice: 14,
    details: 'Expert in prenatal care and obstetrics.',
  },
  {
    name: 'Dr. Charlotte Garcia',
    specialty: 'Gynecologist',
    rating: 4.8,
    image: "",
    consultationCharge: 140,
    hospital: 'Women’s Wellness Clinic',
    yearsOfPractice: 13,
    details: 'Specializes in pelvic health and urogynecology.',
  },
  {
    name: 'Dr. Harper Martinez',
    specialty: 'Gynecologist',
    rating: 4.7,
    image: "",
    consultationCharge: 115,
    hospital: 'Endometriosis Care Center',
    yearsOfPractice: 10,
    details: 'Focuses on treating endometriosis and fibroids.',
  },
  {
    name: 'Dr. Abigail Thompson',
    specialty: 'Gynecologist',
    rating: 4.9,
    image: "",
    consultationCharge: 125,
    hospital: 'Pelvic Health Institute',
    yearsOfPractice: 11,
    details: 'Expert in minimally invasive gynecological surgeries.',
  },
  {
    name: 'Dr. Ella Young',
    specialty: 'Gynecologist',
    rating: 4.8,
    image: "",
    consultationCharge: 130,
    hospital: 'Fertility and Reproductive Health Center',
    yearsOfPractice: 12,
    details: 'Specializes in IVF and assisted reproductive technologies.',
  },
  {
    name: 'Dr. Grace Lee',
    specialty: 'Gynecologist',
    rating: 4.7,
    image: "",
    consultationCharge: 120,
    hospital: "Women's Health and Wellness Center",
    yearsOfPractice: 9,
    details: 'Focuses on adolescent gynecology and sexual health.',
  },
  {
    name: 'Dr. Hannah Hall',
    specialty: 'Gynecologist',
    rating: 4.9,
    image: "",
    consultationCharge: 140,
    hospital: 'Gynecology and Obstetrics Clinic',
    yearsOfPractice: 16,
    details: 'Expert in high-risk pregnancies and maternal-fetal medicine.',
  },
  {
    name: 'Dr. Lily Jackson',
    specialty: 'Gynecologist',
    rating: 4.8,
    image: "",
    consultationCharge: 135,
    hospital: 'Integrative Women’s Health Center',
    yearsOfPractice: 12,
    details: 'Specializes in holistic approaches to women’s health.',
  },
  {
    name: 'Dr. Mia Carter',
    specialty: 'Gynecologist',
    rating: 4.7,
    image: "",
    consultationCharge: 125,
    hospital: 'Obstetrics and Gynecology Associates',
    yearsOfPractice: 11,
    details: 'Focuses on gynecologic oncology and preventive care.',
  },
  {
    name: 'Dr. Nora White',
    specialty: 'Gynecologist',
    rating: 4.9,
    image: "",
    consultationCharge: 145,
    hospital: 'Women’s Healthcare Center',
    yearsOfPractice: 14,
    details: 'Expert in adolescent health and sexual education.',
  },
  {
    name: 'Dr. Sarah Allen',
    specialty: 'Gynecologist',
    rating: 4.8,
    image: "",
    consultationCharge: 130,
    hospital: 'Advanced Gynecology Clinic',
    yearsOfPractice: 10,
    details: 'Specializes in reproductive surgery and fibroid treatment.',
  },
  {
    name: 'Dr. Emily Harris',
    specialty: 'Gynecologist',
    rating: 4.7,
    image: "",
    consultationCharge: 115,
    hospital: 'Complete Women’s Health Center',
    yearsOfPractice: 9,
    details: 'Focuses on health education and preventive screenings.',
  },
  {
    name: 'Dr. Chloe King',
    specialty: 'Gynecologist',
    rating: 4.9,
    image: "",
    consultationCharge: 150,
    hospital: 'Women’s Integrated Health Center',
    yearsOfPractice: 18,
    details: 'Expert in pelvic pain and hormonal disorders.',
  },
  {
    name: 'Dr. Elizabeth Scott',
    specialty: 'Gynecologist',
    rating: 4.8,
    image: "",
    consultationCharge: 140,
    hospital: 'Gynecology Specialists Clinic',
    yearsOfPractice: 12,
    details: 'Specializes in menopause management and hormone therapy.',
  },
  {
    name: 'Dr. William Brown',
    specialty: 'Oncologist',
    rating: 4.9,
    image: "",
    consultationCharge: 200,
    hospital: 'Cancer Care Institute',
    yearsOfPractice: 15,
    details: 'Expert in hematologic malignancies and chemotherapy.',
  },
  {
    name: 'Dr. James Johnson',
    specialty: 'Oncologist',
    rating: 4.8,
    image: "",
    consultationCharge: 220,
    hospital: 'Oncology and Hematology Center',
    yearsOfPractice: 12,
    details: 'Focuses on breast cancer treatment and survivorship.',
  },
  {
    name: 'Dr. Olivia Smith',
    specialty: 'Oncologist',
    rating: 4.7,
    image: "",
    consultationCharge: 210,
    hospital: 'Comprehensive Cancer Center',
    yearsOfPractice: 14,
    details: 'Specializes in immunotherapy and targeted therapies.',
  },
  {
    name: 'Dr. Ava Williams',
    specialty: 'Oncologist',
    rating: 4.9,
    image: "",
    consultationCharge: 230,
    hospital: 'Radiation Oncology Clinic',
    yearsOfPractice: 18,
    details: 'Expert in radiation therapy for various cancers.',
  },
  {
    name: 'Dr. Sophia Davis',
    specialty: 'Oncologist',
    rating: 4.8,
    image: "",
    consultationCharge: 205,
    hospital: 'Cancer Treatment Center',
    yearsOfPractice: 10,
    details: 'Focuses on gynecologic cancers and research.',
  },
  {
    name: 'Dr. Isabella Martinez',
    specialty: 'Oncologist',
    rating: 4.7,
    image: "",
    consultationCharge: 215,
    hospital: 'Oncology Specialists Group',
    yearsOfPractice: 13,
    details: 'Specializes in lung cancer and clinical trials.',
  },
  {
    name: 'Dr. Mia Hernandez',
    specialty: 'Oncologist',
    rating: 4.9,
    image: "",
    consultationCharge: 225,
    hospital: 'Pediatric Oncology Clinic',
    yearsOfPractice: 16,
    details: 'Expert in childhood cancers and supportive care.',
  },
  {
    name: 'Dr. Grace Lee',
    specialty: 'Oncologist',
    rating: 4.8,
    image: "",
    consultationCharge: 235,
    hospital: 'Gastrointestinal Cancer Center',
    yearsOfPractice: 11,
    details: 'Focuses on colorectal cancer treatments and prevention.',
  },
  {
    name: 'Dr. Hannah Wilson',
    specialty: 'Oncologist',
    rating: 4.7,
    image: "",
    consultationCharge: 200,
    hospital: 'Breast Health Center',
    yearsOfPractice: 12,
    details: 'Specializes in early detection and treatment of breast cancer.',
  },
  {
    name: 'Dr. Lily White',
    specialty: 'Oncologist',
    rating: 4.9,
    image: "",
    consultationCharge: 240,
    hospital: 'Comprehensive Cancer Care',
    yearsOfPractice: 14,
    details: 'Expert in melanoma and skin cancers.',
  },
  {
    name: 'Dr. Emily Thompson',
    specialty: 'Oncologist',
    rating: 4.8,
    image: "",
    consultationCharge: 210,
    hospital: 'Sarcoma and Bone Tumor Clinic',
    yearsOfPractice: 9,
    details: 'Focuses on sarcomas and soft tissue tumors.',
  },
  {
    name: 'Dr. Abigail King',
    specialty: 'Oncologist',
    rating: 4.7,
    image: "",
    consultationCharge: 215,
    hospital: 'Lung Cancer Institute',
    yearsOfPractice: 11,
    details: 'Specializes in treatment and research of lung cancer.',
  },
  {
    name: 'Dr. Charlotte Scott',
    specialty: 'Oncologist',
    rating: 4.9,
    image: "",
    consultationCharge: 230,
    hospital: 'Cancer Prevention Center',
    yearsOfPractice: 15,
    details: 'Expert in cancer prevention strategies and education.',
  },
  {
    name: 'Dr. Ella Gonzalez',
    specialty: 'Oncologist',
    rating: 4.8,
    image: "",
    consultationCharge: 220,
    hospital: 'Oncology Clinical Trials Unit',
    yearsOfPractice: 12,
    details: 'Focuses on clinical trials for new cancer therapies.',
  },
  {
    name: 'Dr. Aria Clark',
    specialty: 'Oncologist',
    rating: 4.7,
    image: "",
    consultationCharge: 215,
    hospital: 'Metastatic Cancer Clinic',
    yearsOfPractice: 10,
    details: 'Specializes in palliative care for advanced cancers.',
  },
  {
    name: 'Dr. Scarlett Robinson',
    specialty: 'Oncologist',
    rating: 4.9,
    image: "",
    consultationCharge: 240,
    hospital: 'Blood Cancer Treatment Center',
    yearsOfPractice: 16,
    details: 'Expert in lymphoma and leukemia treatment.',
  },
  {
    name: 'Dr. Victoria Carter',
    specialty: 'Oncologist',
    rating: 4.8,
    image: "",
    consultationCharge: 200,
    hospital: 'Integrative Oncology Center',
    yearsOfPractice: 14,
    details: 'Focuses on holistic approaches to cancer care.',
  },
  {
    name: 'Dr. Grace Moore',
    specialty: 'Oncologist',
    rating: 4.7,
    image: "",
    consultationCharge: 205,
    hospital: 'Colon and Rectal Cancer Institute',
    yearsOfPractice: 10,
    details: 'Specializes in colorectal cancer treatment and research.',
  },
];